from tkinter import *
k = Tk()
result = StringVar()
button1 = Button(k, text="1", width=5, height=2)
button2 = Button(k, text="2", width=5, height=2)
button3 = Button(k, text="3", width=5, height=2)
button4 = Button(k, text="4", width=5, height=2)
button5 = Button(k, text="5", width=5, height=2)
button6 = Button(k, text="6", width=5, height=2)
button7 = Button(k, text="7", width=5, height=2)
button8 = Button(k, text="8", width=5, height=2)
button9 = Button(k, text="9", width=5, height=2)
button0 = Button(k, text="0", width=5, height=2)
button11 = Button(k, text="*", width=5, height=2)
button12 = Button(k, text="/", width=5, height=2)
button13 = Button(k, text="-", width=5, height=2)
button14 = Button(k, text="+", width=5, height=2)
button15 = Button(k, text="=", width=5, height=2)
button16 = Button(k, text=".", width=5, height=2)
button1.grid(row=1, column=0, padx=5, pady=5)
button2.grid(row=1, column=1, padx=5, pady=5)
button3.grid(row=1, column=2, padx=5, pady=5)
button4.grid(row=2, column=0, padx=5, pady=5)
button5.grid(row=2, column=1, padx=5, pady=5)
button6.grid(row=2, column=2, padx=5, pady=5)
button7.grid(row=3, column=0, padx=5, pady=5)
button8.grid(row=3, column=1, padx=5, pady=5)
button9.grid(row=3, column=2, padx=5, pady=5)
button0.grid(row=4, column=1, padx=5, pady=5)
entry = Entry(k, textvariable=result )
entry.grid(row=0, column=0, columnspan=4)
k.mainloop()
